# Generated by Django 4.2.15 on 2024-11-15 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='類別名稱')),
            ],
            options={
                'verbose_name': '菜單類別',
                'verbose_name_plural': '菜單類別',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='標籤名稱')),
            ],
            options={
                'verbose_name': '標籤',
                'verbose_name_plural': '標籤',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='菜名')),
                ('image', models.ImageField(default='menu_images/default.jpg', upload_to='menu_images/', verbose_name='圖片')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='價格')),
                ('available', models.BooleanField(default=True, verbose_name='是否可供應')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='menu.category', verbose_name='所屬類別')),
                ('tags', models.ManyToManyField(blank=True, related_name='menu_items', to='menu.tag', verbose_name='標籤')),
            ],
            options={
                'verbose_name': '菜單項目',
                'verbose_name_plural': '菜單項目',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, verbose_name='Session ID')),
                ('table', models.IntegerField(choices=[(1, '桌號 1'), (2, '桌號 2'), (3, '桌號 3'), (4, '桌號 4'), (5, '桌號 5')], verbose_name='餐桌')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product', verbose_name='菜單項目')),
            ],
            options={
                'verbose_name': '購物車',
                'verbose_name_plural': '購物車管理',
            },
        ),
    ]
