"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# 加載 .env 文件中的環境變數
load_dotenv()

# 設置項目根目錄
BASE_DIR = Path(__file__).resolve().parent.parent

# 安全密鑰（生產環境中應保持機密）
SECRET_KEY = 'django-insecure-x(!%()-67(7wd#ai3rvgx!h6us+zczft0s&%t5n8ba_noz++up'

# 調試模式（生產環境中應設置為 False）
DEBUG = True

# 允許的主機
ALLOWED_HOSTS = []

# 應用程序定義
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # 加入 Django REST framework
    'users',
    'products',
    'order',
]

# 中間件定義
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 根 URL 配置
ROOT_URLCONF = 'core.urls'

# 模板配置
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 確保包含 templates 路徑
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI 應用程序
WSGI_APPLICATION = 'core.wsgi.application'

# 數據庫配置
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 密碼驗證
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 國際化配置
LANGUAGE_CODE = 'zh-hant'  # 設定語言為繁體中文
TIME_ZONE = 'Asia/Taipei'  # 設定時區為台北
USE_I18N = True
USE_TZ = True

# 靜態文件配置
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 媒體文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 默認主鍵字段類型
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 郵件設置（使用 Gmail 作為 SMTP 伺服器）
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "My Store"
EMAIL_HOST_USER = os.getenv("ZOE_EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("ZOE_EMAIL_HOST_PASSWORD")

# 登入和登出重定向配置
LOGIN_URL = '/accounts/login/'  # 指定預設登入頁面
LOGIN_REDIRECT_URL = '/'  # 指定登入成功後的重定向頁面
LOGOUT_REDIRECT_URL = 'product_list'  # 指定登出成功後的重定向頁面

# PayPal 配置
PAYPAL_CLIENT_ID = os.getenv("PAYPAL_CLIENT_ID")
PAYPAL_CLIENT_SECRET = os.getenv("PAYPAL_CLIENT_SECRET")
PAYPAL_MODE = os.getenv("PAYPAL_MODE", "sandbox")  # 默認為 sandbox 模式