"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# 建立專案路徑
BASE_DIR = Path(__file__).resolve().parent.parent

# 快速啟動開發設置 - 不適用於生產環境
# 請參閱 https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# 安全警告：在生產環境中請保持密鑰的秘密！
SECRET_KEY = 'django-insecure-5-&y@g%+x80j0h_lq0237_#q#2&l5jd(@vhum&0czizzhn+bar'

# 安全警告：在生產環境中不要開啟 debug 模式！
DEBUG = True

ALLOWED_HOSTS = []  # 允許的主機列表


# 應用程式定義

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # 加入 Django REST framework
    'customerdata',  # 加入自定義的應用程式
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # 設定模板目錄
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# 資料庫設定
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 使用 MySQL 資料庫
        'NAME': 'crm_db',  # 資料庫名稱
        'USER': 'root',  # 資料庫使用者
        'PASSWORD': 'Root123~',  # 資料庫密碼
        'HOST': 'localhost',  # 資料庫主機
        'PORT': '3306',  # 資料庫連接埠
    }
}


# 密碼驗證
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# 國際化設定
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hant'  # 設定語言為繁體中文

TIME_ZONE = 'Asia/Taipei'  # 設定時區為台北

USE_I18N = True

USE_TZ = True


# 靜態檔案 (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'  # 靜態檔案的 URL 路徑

# 預設主鍵欄位類型
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'