# Generated by Django 5.1.1 on 2024-11-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="date",
            field=models.DateField(),
        ),
    ]
