# Generated by Django 5.1.5 on 2025-01-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
    ]
