# Generated by Django 5.1.1 on 2024-11-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='未提供', max_length=255, verbose_name='配送地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='未提供', max_length=20, verbose_name='聯絡電話'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '未支付'), ('processing', '準備中'), ('shipped', '已出貨'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='訂單狀態'),
        ),
    ]
