# Generated by Django 5.1.1 on 2024-11-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursegrade",
            name="adjusted_grade",
            field=models.FloatField(blank=True, null=True, verbose_name="調整後成績"),
        ),
    ]
