# Generated by Django 5.1.1 on 2024-11-22 06:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("assignment", "student")},
        ),
    ]
