# Generated by Django 4.2.15 on 2024-11-15 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False, verbose_name='訂單號碼')),
                ('table', models.IntegerField(choices=[(1, '桌號 1'), (2, '桌號 2'), (3, '桌號 3'), (4, '桌號 4'), (5, '桌號 5')], verbose_name='餐桌')),
                ('status', models.CharField(choices=[('PENDING', '待處理'), ('PREPARING', '準備中'), ('SERVED', '已送達'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='PENDING', max_length=10, verbose_name='訂單狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單管理',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='項目總價')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product', verbose_name='菜單項目')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='訂單')),
            ],
            options={
                'verbose_name': '訂單項目',
                'verbose_name_plural': '訂單項目管理',
            },
        ),
    ]
