# Generated by Django 5.1.1 on 2024-11-19 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AddField(
            model_name='booking',
            name='double_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='quad_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='single_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='six_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
