# Generated by Django 5.1.1 on 2024-11-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_booking_room_booking_double_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('DEPOSIT_PAID', '已付訂金'), ('CANCELLED', '已取消'), ('COMPLETED', '已完成')], default='DEPOSIT_PAID', max_length=20),
        ),
    ]
