# Generated by Django 4.2.15 on 2024-12-12 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='帳戶名稱')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='帳戶餘額')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '帳戶',
                'verbose_name_plural': '帳戶',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='類別名稱')),
            ],
            options={
                'verbose_name': '類別',
                'verbose_name_plural': '類別',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='記帳項目名稱')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金額')),
                ('is_income', models.BooleanField(default=False, verbose_name='收入')),
                ('date', models.DateField(verbose_name='日期')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.account', verbose_name='帳戶')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.category', verbose_name='類別')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '記帳',
                'verbose_name_plural': '記帳',
                'ordering': ('-date',),
            },
        ),
    ]
